timeoutInS:        300
repository:        git@github.com:SimonEbner/navigation_test_results
bagPath:           jenkins@cob-sim2:/home/webportal/bagfiles
setupRobotService: setup_robot
collisionsTopic:   collisions
cameraTopics:      [ /topCamera ]
moveBaseAction:    /move_base
