timeoutInS:        300
repository:        git@github.com:SimonEbner/navigation_test_results
bagPath:           /u/uhr-se/bagfiles
setupRobotService: setup_robot
collisionsTopic:   collisions
cameraTopics:      [ ]
moveBaseAction:    /move_base
