timeoutInS:        300
repository:        git@github.com:SimonEbner/navigation_test_results
bagPath:           /tmp/bagrecord
collisionsTopic:   collisions
cameraTopics:      [ /camera/rgb/image_color ]
