timeoutInS:        100
repository:        git@github.com:SimonEbner/navigation_test_results
bagPath:           /tmp/bagrecord
setupRobotService: setup_robot
collisionsTopic:   collisions
cameraTopics:      [ /camera/rgb/image_color ]
