timeoutInS:        500
repository:        git@github.com:SimonEbner/navigation_test_results_sim
bagPath:           /share/uhr-se/bagrecord
setupRobotService: setup_robot
collisionsTopic:   collisions
cameraTopics:      [ /topCamera/image_raw ]
